### ISSUE TITLE
n-tuplize miniAOD with FSA

### ISSUE THREAD

**Issue by dabelknap** [uwcms/FinalStateAnalysis#349]
@mcepeda @isobelojalvo @dntaylor @nwoods

With the new miniAOD format coming out, we need to see if FSA can be modified to n-tuplize the new format. We don't need to worry about PAT-tuplization, since they are no longer relevant for miniAOD.

A new branch `miniAOD_dev` has been created in uwcms/FSA. Please send any related pull-requests to this branch.

Devin, if you have any code committed, go ahead and submit a pull request (even if it isn't ready yet), so we can track the progress, and please reference the PR in this issue. Thanks.

**Comment by dntaylor** [comment]
I think we can close this issue. The miniAOD branch works. Further development can reference a new issue as we get closer to startup.
