### ISSUE TITLE
Error building master

### ISSUE THREAD

**Issue by nwoods** [uwcms/FinalStateAnalysis#386]
I haven't used master (or anything else in CMSSW_5) in a long time, and honestly haven't really followed the development either, so sorry if my mistake is obvious.

I'm getting an error near the end of the build process on the master branch, it looks like it might be a linker issue?

```
terminate called after throwing an instance of 'edm::Exception'
  what():  An exception of category 'FileInPathError' occurred.
Exception Message:
edm::FileInPath unable to find file FinalStateAnalysis/DataAlgos/data/pileup_distributions.py anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /afs/hep.wisc.edu/cms/nwoods/fsa8TeV/src:/afs/hep.wisc.edu/cms/nwoods/fsa8TeV/external/slc6_amd64_gcc472/data:/cvmfs/cms.cern.ch/slc6_amd64_gcc472/cms/cmssw-patch/CMSSW_5_3_14_patch2/src:/cvmfs/cms.cern.ch/slc6_amd64_gcc472/cms/cmssw-patch/CMSSW_5_3_14_patch2/external/slc6_amd64_gcc472/data
Current directory is: /afs/hep.wisc.edu/cms/nwoods/fsa8TeV

/bin/sh: line 1: 29485 Aborted                 ( LD_LIBRARY_PATH=$LOCALTOP/tmp/slc6_amd64_gcc472/src/FinalStateAnalysis/DataFormats/src/FinalStateAnalysisDataFormats:$LD_LIBRARY_PATH /cvmfs/cms.cern.ch/slc6_amd64_gcc472/cms/cmssw-patch/CMSSW_5_3_14_patch2/src/FWCore/Utilities/scripts/edmCheckClassVersion -l libFinalStateAnalysisDataFormatsCapabilities.so -x $x )
>> Building shared library tmp/slc6_amd64_gcc472/src/FinalStateAnalysis/NtupleTools/src/FinalStateAnalysisNtupleTools/libFinalStateAnalysisNtupleTools.so
>> Building binary TestFinalStateAnalysisUtilities
gmake: *** [tmp/slc6_amd64_gcc472/src/FinalStateAnalysis/DataFormats/src/FinalStateAnalysisDataFormats/libFinalStateAnalysisDataFormatsCapabilities.so] Error 1
gmake: *** Waiting for unfinished jobs....
```

I build with

```
 1004  scram pro -n fsa8TeV CMSSW CMSSW_5_3_14_patch2
 1005  cd fsa8TeV/src/
 1006  cmsenv
 1007  eval `ssh-agent -s`
 1008  ssh-add
 1009  git cms-init
 1010  git clone --recursive https://github.com/uwcms/FinalStateAnalysis.git
 1011    cd FinalStateAnalysis
 1012  cd recipe/
 1013  PATPROD=1 LUMI=1 LIMITS=0 ./recipe.sh
 1014  cd ../..
 1015  export USER_CXXFLAGS="-Wno-delete-non-virtual-dtor -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=sign-compare -Wno-error=reorder"
 1016    scram b -j 8
```

At first, I thought this was a fluke caused by my ssh tunnel crashing during a previous compile, but `scram b clean` didn't fix it. I tried deleting the whole release and trying again from scratch, but this gave the same result. `pileup_distributions.py` is in the expected folder, so that's not the issue.

Anybody know what's going on?

**Comment by mcepeda** [comment]
Hi Nate,

Which machine is this? I know I recently compiled 53X_SLC6_Dev - but the differences are minimal between that and the master.

Maria

**Comment by nwoods** [comment]
Login01

**Comment by nsmith-** [comment]
I recently compiled master on login06, no idea what is different on the machines.
You could try `scram b -v` for some more verbosity maybe?
[Here](https://github.com/cms-sw/cmssw/blob/63bf2bd4374026cc3ae8395a0b17471ffcc1c230/FWCore/ParameterSet/src/FileInPath.cc#L483) is the error message source

**Comment by mcepeda** [comment]
I tried compiling right now from login06. And I get your same error.
But, this was working last week. And nobody touched the master, so I am rather puzzled.
The login machines are working very bizarrely right now - I wonder if this could be related.
Maria

**Comment by nwoods** [comment]
They are acting really weird lately -- has anybody been in touch with Dan et al. about this? I haven't just because I haven't been clever enough to notice consistent enough patterns in their behavior for any debugging to occur. 

I copied Devin's most recent area, which is a commit or two behind master, and it compiled fine. What CMSSW did you use? My failing areas were `CMSSW_5_3_14_patch2` while his working version was `CMSSW_5_3_14`.

**Comment by nsmith-** [comment]
I compiled within the last two days on `CMSSW_5_3_14`

**Comment by mcepeda** [comment]
I think you might have it there nate. Dont use the patch. We were using CMSSW_5_3_14, no patch, before. 

(And, from past experience, dont go to CMSSW_5_3_2X unless you def. need to, and if you really do tell me because I got it to compile with some work, but I had to kill a few things you will very likely need)

**Comment by dabelknap** [comment]
Do you get the same error if you compile with `scram b -j 1`? Sometimes error messages get scrambled when you run multiple jobs, and the output is misleading.

**Comment by nwoods** [comment]
I don't remember how this was eventually resolved, but it's old and irrelevant now so I'm closing it.
