### ISSUE TITLE
Ghost cleaning

### ISSUE THREAD

**Issue by nwoods** [uwcms/FinalStateAnalysis#390]
My analysis requires muons to be ghost cleaned with code like

```
process.cleanedMu = cms.EDProducer("PATMuonCleanerBySegments",
   src = cms.InputTag("calibratedMuons"),
   preselection = cms.string("track.isNonnull"),
   passthrough = cms.string("isGlobalMuon && numberOfMatches >= 2"),
   fractionOfSharedSegments = cms.double(0.499))
```

Is this valuable enough to everyone that I should put it in the main path or should I make it an option? It seems like everyone would want it, or something similar, but it's not in the master branch so I don't want to put it in without asking.

**Comment by mcepeda** [comment]
Most of that is already the definition of a good muon, so, sure.

**Comment by nwoods** [comment]
I will add it.
