### ISSUE TITLE
Automatic FSA Validation

### ISSUE THREAD

**Issue by dntaylor** [uwcms/FinalStateAnalysis#402]
Hi All,

There has been some discussion recently on validating FSA more efficiently. I decided to look into how CMSSW does it. They do it through a tool called [Jenkins](https://jenkins-ci.org/). This is a very generic framework that can do a lot of things (validating github repositories, SVN, custom workflows, w/e). I propose we adapt this to work with FSA.

The proposed workflow would become:
- You write your amazing code
- Commit your changes to your local fork of FSA
- Submit a pull request to the uwcms FSA
  - Jenkins will check every 5 mins for new PR
  - The PR is automatically cloned into a new workspace and built
  - While this is happening, the status will change to Pending
  - On successful compilation the status will change to Success
  - If it fails, the status will change to Failed
- The project could then be merged

Lots of neat features could be added to this. For example, a script could be run after building that compares histograms for each final state and ntuple row on a bin-by-bin basis. Or someone could add a sync plugin that compares to a full analysis chain sync.

In addition, this program could create pre-built tar files that could be downloaded and thus make it so others do not need to compile the code.

Anyway, I have deployed a test setup on my computer at CERN. You can view the [running server here](http://137.138.236.135:8080/). This is currently monitoring my own fork of FSA and you can see a test of the functionality on [this test PR](https://github.com/dntaylor/FinalStateAnalysis/pull/1).

It is limited since our old CERN computers only have 2 cores. I can therefore only do `scram b` with 1 core. But if this is something we want we can set this up to run on a login machine, or via a CERN virtual machine, with far more cores. Also note, at the moment I have it redo the full compilation and recipe each time. This could be modified to check for recent file changes and only compile the appropriate module that was updated, or rerun a portion of the recipe (as Maria requested yesterday).

**Comment by mverzett** [comment]
Hi Dan,

If I recall correctly Jenkins was already set up (~2 years ago) for FSA, I think is a Wisconsin login machine. 
Maybe @tsarangi knows more about it, as I did not take part in any of it.

**Comment by nwoods** [comment]
This is a great idea, thanks for taking the initiative on it. 

I haven't looked at the details of this at all so I don't know how it evaluates whether or not the test worked... could we have it grab a particular file and run the DQM ntuplizer on it? At first we can just make sure it doesn't crash over 1000 events or something, but later it would be nice to make sure that some key variables are the same in the output row-by-row. 

This kind of thing isn't what the login machines are for. I think we should set it up on some random machine on the HEP cluster or on a CERN OpenStack instance.

**Comment by mcepeda** [comment]
@ekfriis, do you still read this? :). Which machine did you set up Jenkins in?

(There might even be a issue with the description of how he set it up, back from the golden days of FSA...)

**Comment by mverzett** [comment]
Also consider that the login machines changed physically and OS from then. Jenkins might have been a collateral damage.

**Comment by dntaylor** [comment]
Hi Mauro,
I did grep around a bit and couldn't find it. But yes, I see issues referencing it back in the day (but not the setup).

**Comment by ekfriis** [comment]
HELLO!

It ran on login06 - it was always a kludge and I meant to eventually set it up on a dedicated machine.

You might look in my scratch area on login06, if it still exists. Basically it worked with gigantic gross shell script that setup a CMSSW area, built, ran the recipe and ran a fake job.

Good luck! Let me know if you guys have any questions I might be able to help with (but I will require authorship ;) I hope you guys are all doing great! When does the machine turn on? When is ATLAS going to release an LFV analysis???

**Comment by nwoods** [comment]
This is up and running! Right now it just builds, but an automated version of @dntaylor's sweet DQM suite is coming soon. Interested parties can check it out: http://leeroy.hep.wisc.edu:8080/

**Comment by ekfriis** [comment]
CMSSW 7???? Wow, the future is here!

**Comment by mverzett** [comment]
...and you have not seen ROOT6! Still have to try it though, usually bugs are proportional to the release :)

**Comment by nwoods** [comment]
Pretty soon we're turning all those final state options into a single variadic template. After that, flying cars.

**Comment by ekfriis** [comment]
I wouldn't ride in a flying car powered by ROOT6. Need at least ROOT8 or 9
for me to feel comfortable.

 **\* Break **\* segmentation violation
Traceback (most recent call last):
  File "/u/kocolosk/afsdir/scripts/mergeTrees.py", line 150, in ?
    sys.exit(main())
  File "/u/kocolosk/afsdir/scripts/mergeTrees.py", line 141, in main
    [mergeOther(li,'chargedPionTree') for li in listsOfFiles if len(li) > 1]
  File "/u/kocolosk/afsdir/scripts/mergeTrees.py", line 97, in mergeOther
    outputTree = ROOT.TTree.MergeTrees(collection)
SystemError: problem in C++; program state has been reset

**Comment by nwoods** [comment]
It's not so bad except that right and left turns work completely differently and it only comes in grey.
