### ISSUE TITLE
Moving the miniAOD 74X branch to master ?

### ISSUE THREAD

**Issue by mcepeda** [uwcms/FinalStateAnalysis#444]
@dntaylor , @nwoods  (et all), why dont we do the migration?

**Comment by nwoods** [comment]
I would support this. Is anyone still using the 8 TeV version frequently?

**Comment by tmrhombus** [comment]
We just started a new set of FSA patTuples this past Thursday which are still running.  But I don't really care if this isn't the master branch any more as long as there's some branch that has this version saved.

**Comment by nwoods** [comment]
Of course there would be. The real question is whether or not the 8 TeV version is still under development, as that determines whether we make it a tag or just a branch.

**Comment by tmrhombus** [comment]
I think a tag should be fine
