### ISSUE TITLE
Error in producing ntuples using 76

### ISSUE THREAD

**Issue by Nabarun21** [uwcms/FinalStateAnalysis#472]
I get the following errors when trying to produce ntuples using the 76X branch. 

`Begin processing the 1st record. Run 1, Event 9783, LumiSection 50 at 21-Jan-2016 08:29:12.295 CST 
terminate called after throwing an instance of 'cms::Exception'
  what():  An exception of category 'UnknownUserInt' occurred.
Exception Message:
Requested UserInt CBIDLoose is not available! Possible UserInts are:
ElectronMVAEstimatorRun2Spring15NonTrig25nsV1Categories ElectronMVAEstimatorRun2Spring15Trig25nsV1Categories ElectronMVAEstimatorRun2Spring15\
Trig50nsV1Categories`

Also,

`Begin processing the 1st record. Run 1, Event 999, LumiSection 6 at 21-Jan-2016 08:23:28.628 CST
terminate called after throwing an instance of 'cms::Exception'
  what():  An exception of category 'UnknownUserFloat' occurred.
Exception Message:
Requested UserFloat cand_dM_0 is not available! Possible UserFloats are:
cand_dM`

This is where it `cbidloose` appears to be getting defined and filled in.
https://github.com/Nabarun21/FinalStateAnalysis/blob/miniAOD_dev_76X/NtupleTools/python/customization_electrons.py#L104

https://github.com/Nabarun21/FinalStateAnalysis/blob/miniAOD_dev_76X/PatTools/plugins/MiniAODElectronIDEmbedder.cc#L138

Can anyone help me with this?

**Comment by dntaylor** [comment]
I only tested with electrons and muons. @truggles has issued #470 to fix. It is now merged. So retry.

**Comment by Nabarun21** [comment]
Ok. Retrying.

**Comment by Nabarun21** [comment]
It's failing again with similar/same errors. It can't fins userInt/useFloats like CBIDLoose above. I was trying to run on the following datasets:
`data_SingleElectron_Run2015C_16Dec2015_25ns`
`WW_TuneCUETP8M1_13TeV-pythia8` with campaign tag `RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1`

**Comment by taroni** [comment]
Hi, I found the problem. 
In NtupleTools/python/parameters/default.py line 18 and 51, we need to change the userInt("CBIDLoose") to userFloat("CBIDLoose"). 
I changed it in my local version and I got another error:
terminate called after throwing an instance of 'cms::Exception'
  what():  An exception of category 'UnknownUserFloat' occurred.
Exception Message:
Requested UserFloat cand_dM_0 is not available! Possible UserFloats are: 
cand_dM 

S

**Comment by taroni** [comment]
Ok, I've seen that this has been already solved with pull request #470

**Comment by taroni** [comment]
I've submitted a pull request for this bug

**Comment by Nabarun21** [comment]
Great. It works now after the above fixes.
