### ISSUE TITLE
eVetoMVAIso

### ISSUE THREAD

**Issue by taroni** [uwcms/FinalStateAnalysis#478]
Dear all, 
I was trying to run the LFV Higgs analyser (mu-tau) on a MC sample in 76X and I faced a problem with the eVetoMVAIso branch. As it was not present in the ntuple, I added it and tried to re-run the ntuplizer.
The ntuplizer crashed with the following message

terminate called after throwing an instance of 'cms::Exception'
 what():  An exception of category 'UnknownUserInt' occurred.
Exception Message:
Requested UserInt mvaidwp is not available! Possible UserInts are: 
ElectronMVAEstimatorRun2Spring15NonTrig25nsV1Categories ElectronMVAEstimatorRun2Spring15Trig25nsV1Categories ElectronMVAEstimatorRun2Spring15Trig50nsV1Categories 

I tried to understand why this userInt is not present but I didn’t find any difference with the 74X
Did you already faced this problem? 
Do you have any idea of where it can come from?

Thanks a lot, 
Cheers, 
Silvia

**Comment by dntaylor** [comment]
Hi Silvia.

76X is now strict with userInts and userFloats. If it doesn't exist it throws an error, whereas before it would return a default value. Also, if it is a userFloat but you call it as a userInt it will throw and error. So, need to make sure mvaidwp is actually embedded.  This used to be embedded as part of the pat sequence. Thus it has not been in since we switched to miniAOD. Add a producer for electrons that add the relevant working point to the electrons.

Devin

**Comment by mcepeda** [comment]
Hi,

In the meanwhile, maybe https://github.com/uwcms/FinalStateAnalysis/blob/miniAOD_dev_74X/NtupleTools/python/templates/cleaning.py#L34 can just be changed to read from the same userFloat as https://github.com/uwcms/FinalStateAnalysis/blob/miniAOD_dev_74X/NtupleTools/python/templates/electrons.py#L31 -or any other similar line-?

(In other words, do we need that embedded ID? Wont one of the userFloats work? We need a looseElectron veto, but I dont think we need to be very particular about the working point as long as it is compatible with the electron selection in the analysis)

Best,

Maria

**Comment by nwoods** [comment]
IMO, most of those items should be moved to the analysis-specific parameter files. Basically all except those that use the most common centrally-produced IDs. For example, I have mine set up like [this](https://github.com/uwcms/FinalStateAnalysis/blob/miniAOD_dev_76X/NtupleTools/python/parameters/zz.py#L136).

**Comment by Nabarun21** [comment]
I tried doing the bit suggested by @mcepeda above.
https://github.com/Nabarun21/FinalStateAnalysis/blob/miniAOD_dev_76X/NtupleTools/python/templates/cleaning.py#L37

It appears to be working for me now.
