### ISSUE TITLE
new branch for CMSSW_8_0_13

### ISSUE THREAD

**Issue by taroni** [uwcms/FinalStateAnalysis#523]
Hi all, 
I've created in my repository a new branch for making the FSA working. The error in compiling FSA wiht CMSSW_8_0_13 depends on file "CondFormats/BTauObjects/interface/BTagCalibrationReader.h". In CMSSW_8_0_13 it doesn't exist anymore. The new path to the file is  "CondTools/BTau/interface/BTagCalibrationReader.h"

Do you know how  to proceed? should I create in the official FSA repository a branch that is the clone of the MiniAOD_8_0_X and merge my branch with this new? 
I don't want to merge the fix in MiniAOD_8_0_X: it will stop working in any release < 8_0_13

Thanks a lot, 
Cheers, 
S.

**Comment by truggles** [comment]
Hello Silvia,

I prefer your idea of an 8_0_13 branch in FSA based off of a clone of 8_0_X and your work. Like you said, it would be best if those of us who aren't ready to make the jump to 13 don't have to today.  Thank you for getting this working.

Best,
Tyler

**Comment by mcepeda** [comment]
I second the idea of a new 8_0_13 branch

**Comment by taroni** [comment]
I've created the new miniAOD_8_0_13 branch.
