### ISSUE TITLE
Problem with cython proxy wrapper in FSA/PlotTools/rake/cython.rake

### ISSUE THREAD

**Issue by psiddire** [uwcms/FinalStateAnalysis#582]
I am on branch miniaod_9_4_0 of FSA using CMSSW_9_4_8 and I am trying to run the setup in UWHiggs which contains the following two lines:
rake "make_wrapper[$afile, mt/final/Ntuple, MuTauTree]"                                                                                                        
ls *pyx | sed "s|pyx|so|" | xargs rake

When I run the setup I am getting the following error:
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/gcc/6.3.0/include/c++/6.3.0/bits/c++14_warning.h:32:2: error: #error This file requires compiler and library support for the forthcoming ISO C++ 2014 standard. This support is currently experimental, and must be enabled with the -std=c++1y or -std=gnu++1y compiler options.
 #error This file requires compiler and library support for the forthcoming

error: command 'gcc' failed with exit status 1
rake aborted!
Command failed with status (1): [python MuTauTree_setup.py build_ext --inpl...]

I tried to resolve this by putting -std=c++1y in the CXXFLAGS options in the environment.sh but the error is persistent.

Does anyone know how to resolve this?

**Comment by truggles** [comment]
Hi, can you point to the exact setup recipe you are using?  Or just copy it here?

**Comment by psiddire** [comment]
Hi,

These are the lines in my setup:

export afile=`find $datasrc/$jobid | grep root | head -n 1`


## Build the cython wrappers


rake "make_wrapper[$afile, mt/final/Ntuple, MuTauTree]"

ls *pyx | sed "s|pyx|so|" | xargs rake



Prasanna,
CERN
385 Route de Meyrin
1217 Meyrin

**Comment by truggles** [comment]
I'm not sure about others, but the last time I used the rake / cython code in FSA was in CMSSW_5_3_X on Run-I data.  I do not think anyone has tried to adopt that code to Run-II.  If you want to use this feel free to update it to Run-II and make a PR.

Otherwise, it should probably be removed from FSA.

**Comment by psiddire** [comment]
Hi Tyler,

That code was used with CMSSW_8_0_25 for the Run-II 2016 analysis.

Prasanna,
CERN
385 Route de Meyrin
1217 Meyrin

**Comment by truggles** [comment]
I do not know the solution here sorry.  It is good to know that this ran in 8_0_25 so you have a working example only 1 CMSSW release ago.
